import type { RegistryItemDef } from "../../src/types";

export const ui: RegistryItemDef[] = [
  {
    item: {
      name: "chat-input",
      type: "registry:ui",
      title: "Chat input",
      description: "Chat input with mentions and streaming status.",
      dependencies: [
        "@tiptap/core",
        "@tiptap/react",
        "@tiptap/starter-kit",
        "@tiptap/extension-mention",
        "@tiptap/extension-placeholder",
        "@tiptap/suggestion",
        "ai",
      ],
      registryDependencies: ["input-group"],
      files: [{ path: "chat-input.tsx", type: "registry:ui" }],
    },
    preview: "examples/chat-input-demo",
  },
  {
    item: {
      name: "reasoning",
      type: "registry:ui",
      title: "Reasoning",
      description: "Quiet thinking row with markdown.",
      dependencies: ["streamdown"],
      registryDependencies: ["collapsible"],
      files: [{ path: "reasoning.tsx", type: "registry:ui" }],
    },
    preview: "examples/reasoning-demo",
  },
  {
    item: {
      name: "shell",
      type: "registry:ui",
      title: "Shell",
      description: "Sidebar, header, and main content.",
      registryDependencies: ["button", "sidebar"],
      meta: { fullBleed: true, iframeHeight: 720 },
      files: [{ path: "shell.tsx", type: "registry:ui" }],
    },
    preview: "examples/shell-demo",
  },
  {
    item: {
      name: "tool",
      type: "registry:ui",
      title: "Tool",
      description: "Quiet collapsible tool call with input and output.",
      dependencies: ["ai"],
      registryDependencies: ["collapsible"],
      files: [{ path: "tool.tsx", type: "registry:ui" }],
    },
    preview: "examples/tool-demo",
  },
  {
    item: {
      name: "worked",
      type: "registry:ui",
      title: "Worked",
      description: "Fold the agent's work. Keep the answer.",
      registryDependencies: ["collapsible"],
      files: [{ path: "worked.tsx", type: "registry:ui" }],
    },
    preview: "examples/worked-demo",
  },
  {
    item: {
      name: "world-card",
      type: "registry:ui",
      title: "World card",
      description: "Spatial chrome for in-world cards in React Three Fiber.",
      dependencies: ["three", "@react-three/fiber", "@types/three"],
      files: [
        { path: "world-card.tsx", type: "registry:ui" },
        { path: "world-card-chrome.ts", type: "registry:lib" },
      ],
    },
    preview: "examples/world-card-demo",
  },
  {
    item: {
      name: "xr-button",
      type: "registry:ui",
      title: "XR button",
      description: "Hover and press button for in-world uikit.",
      dependencies: ["@react-three/uikit"],
      registryDependencies: ["@simple-ai/world-card"],
      files: [{ path: "xr-button.tsx", type: "registry:ui" }],
    },
    preview: "examples/xr-button-demo",
  },
  {
    item: {
      name: "xr-chat-input",
      type: "registry:ui",
      title: "XR chat input",
      description: "uikit field and send for in-world chat.",
      dependencies: ["@react-three/uikit", "@react-three/uikit-lucide"],
      registryDependencies: ["@simple-ai/world-card", "@simple-ai/xr-button"],
      files: [{ path: "xr-chat-input.tsx", type: "registry:ui" }],
    },
    preview: "examples/xr-chat-input-demo",
  },
  {
    item: {
      name: "xr-tool",
      type: "registry:ui",
      title: "XR tool",
      description: "Quiet collapsible tool line for in-world chat.",
      dependencies: ["@react-three/uikit", "@react-three/uikit-lucide"],
      registryDependencies: [
        "@simple-ai/world-card",
        "@simple-ai/tool",
        "@simple-ai/xr-markdown",
      ],
      files: [{ path: "xr-tool.tsx", type: "registry:ui" }],
    },
    preview: "examples/xr-tool-demo",
  },
  {
    item: {
      name: "xr-worked",
      type: "registry:ui",
      title: "XR worked",
      description: "Fold the agent's work in world space. Keep the answer.",
      dependencies: ["@react-three/uikit", "@react-three/uikit-lucide"],
      registryDependencies: ["@simple-ai/world-card", "@simple-ai/worked"],
      files: [{ path: "xr-worked.tsx", type: "registry:ui" }],
    },
    preview: "examples/xr-worked-demo",
  },
  {
    item: {
      name: "xr-reasoning",
      type: "registry:ui",
      title: "XR reasoning",
      description: "Quiet thinking row for in-world chat.",
      dependencies: ["@react-three/uikit", "@react-three/uikit-lucide"],
      registryDependencies: ["@simple-ai/world-card", "@simple-ai/xr-markdown"],
      files: [{ path: "xr-reasoning.tsx", type: "registry:ui" }],
    },
    preview: "examples/xr-reasoning-demo",
  },
  {
    item: {
      name: "xr-markdown",
      type: "registry:ui",
      title: "XR markdown",
      description: "MSDF-safe markdown for in-world uikit.",
      dependencies: [
        "@react-three/uikit",
        "@types/mdast",
        "mdast-util-from-markdown",
        "mdast-util-gfm",
        "micromark-extension-gfm",
      ],
      registryDependencies: ["@simple-ai/world-card"],
      files: [{ path: "xr-markdown.tsx", type: "registry:ui" }],
    },
    preview: "examples/xr-markdown-demo",
  },
];
