// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
	"app-layout": {
		name: "app-layout",
		description:
			"A comprehensive layout system with sidebar navigation, resizable panels, and organized content areas.",
		type: "registry:ui",
		registryDependencies: ["button", "resizable", "separator", "sidebar"],
		files: [
			{
				path: "./src/ui-registry/registry/ui/app-layout.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/ui/app-layout.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-layout";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-breadcrumbs": {
		name: "app-breadcrumbs",
		description: "A breadcrumb component for the application.",
		type: "registry:ui",
		registryDependencies: ["breadcrumb"],
		files: [
			{
				path: "./src/ui-registry/registry/ui/app-breadcrumbs.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/ui/app-breadcrumbs.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-breadcrumbs";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-01": {
		name: "app-01",
		description: "An example app layout with a sidebar and a main content area.",
		type: "registry:block",
		registryDependencies: ["button"],
		files: [
			{
				path: "./src/ui-registry/registry/blocks/app-01/page.tsx",
				type: "registry:block",
				target: "",
			},
			{
				path: "./src/ui-registry/registry/blocks/app-01/components/app-sidebar.tsx",
				type: "registry:block",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/blocks/app-01/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-01";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-layout-basic": {
		name: "app-layout-basic",
		description: "Simple layout with header and content using AppSidebar",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-layout-basic.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-layout-basic.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-layout-basic";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-layout-no-header": {
		name: "app-layout-no-header",
		description: "Minimal layout without header for cleaner interfaces",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-layout-no-header.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-layout-no-header.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-layout-no-header";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-layout-with-actions": {
		name: "app-layout-with-actions",
		description: "Layout using AppLayoutHeaderActions for buttons and controls",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-layout-with-actions.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-layout-with-actions.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-layout-with-actions";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-layout-custom-sidebar": {
		name: "app-layout-custom-sidebar",
		description: "Layout with a custom sidebar instead of the default AppSidebar",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-layout-custom-sidebar.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-layout-custom-sidebar.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-layout-custom-sidebar";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-layout-resizable": {
		name: "app-layout-resizable",
		description: "Layout with resizable primary and secondary panels",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-layout-resizable.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-layout-resizable.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-layout-resizable";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-layout-collapsed": {
		name: "app-layout-collapsed",
		description: "Layout that starts with sidebar collapsed by default",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-layout-collapsed.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-layout-collapsed.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-layout-collapsed";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-breadcrumbs-home": {
		name: "app-breadcrumbs-home",
		description: "Basic breadcrumbs showing Home link (default behavior)",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-breadcrumbs-home.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-breadcrumbs-home.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-breadcrumbs-home";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-breadcrumbs-no-home": {
		name: "app-breadcrumbs-no-home",
		description: "Breadcrumbs without the default Home link using showHome=false",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-breadcrumbs-no-home.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-breadcrumbs-no-home.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-breadcrumbs-no-home";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
	"app-breadcrumbs-nested": {
		name: "app-breadcrumbs-nested",
		description: "Multi-level breadcrumbs for deep navigation structures",
		type: "registry:example",
		registryDependencies: [],
		files: [
			{
				path: "./src/ui-registry/registry/examples/app-breadcrumbs-nested.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/ui-registry/registry/examples/app-breadcrumbs-nested.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) => typeof mod[key] === "function" || typeof mod[key] === "object",
				) || "app-breadcrumbs-nested";
			return { default: mod.default || mod[exportName] };
		}),
		categories: [],
		meta: {},
	},
};
