// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "app-layout": {
    name: "app-layout",
    description: "A comprehensive layout system with sidebar navigation, resizable panels, and organized content areas.",
    type: "registry:ui",
    registryDependencies: ["button","resizable","separator","sidebar"],
    files: [{
      path: "./src/ui-registry/registry/ui/app-layout.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/ui/app-layout.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "app-layout"
      return { default: mod.default || mod[exportName] }
    }),
    categories: [],
    meta: {},
  },
  "app-breadcrumbs": {
    name: "app-breadcrumbs",
    description: "A breadcrumb component for the application.",
    type: "registry:ui",
    registryDependencies: ["breadcrumb"],
    files: [{
      path: "./src/ui-registry/registry/ui/app-breadcrumbs.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/ui/app-breadcrumbs.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "app-breadcrumbs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: [],
    meta: {},
  },
  "app-01": {
    name: "app-01",
    description: "An example app layout with a sidebar and a main content area.",
    type: "registry:block",
    registryDependencies: ["button"],
    files: [{
      path: "./src/ui-registry/registry/blocks/app-01/page.tsx",
      type: "registry:block",
      target: ""
    },{
      path: "./src/ui-registry/registry/blocks/app-01/components/app-sidebar.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/blocks/app-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "app-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: [],
    meta: {},
  },
  "button-default": {
    name: "button-default",
    description: "A standard button with the default styling.",
    type: "registry:example",
    registryDependencies: ["@/components/ui/button"],
    files: [{
      path: "./src/ui-registry/registry/examples/button-default.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/examples/button-default.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-default"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["button"],
    meta: {},
  },
  "button-secondary": {
    name: "button-secondary",
    description: "A secondary button with muted styling.",
    type: "registry:example",
    registryDependencies: ["@/components/ui/button"],
    files: [{
      path: "./src/ui-registry/registry/examples/button-secondary.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/examples/button-secondary.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-secondary"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["button"],
    meta: {},
  },
  "button-outline": {
    name: "button-outline",
    description: "A button with an outline border and transparent background.",
    type: "registry:example",
    registryDependencies: ["@/components/ui/button"],
    files: [{
      path: "./src/ui-registry/registry/examples/button-outline.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/examples/button-outline.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-outline"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["button"],
    meta: {},
  },
  "button-ghost": {
    name: "button-ghost",
    description: "A subtle button with minimal styling.",
    type: "registry:example",
    registryDependencies: ["@/components/ui/button"],
    files: [{
      path: "./src/ui-registry/registry/examples/button-ghost.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/examples/button-ghost.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-ghost"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["button"],
    meta: {},
  },
  "button-destructive": {
    name: "button-destructive",
    description: "A button for destructive actions, typically red.",
    type: "registry:example",
    registryDependencies: ["@/components/ui/button"],
    files: [{
      path: "./src/ui-registry/registry/examples/button-destructive.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/examples/button-destructive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-destructive"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["button"],
    meta: {},
  },
  "button-link": {
    name: "button-link",
    description: "A button styled to look like a text link.",
    type: "registry:example",
    registryDependencies: ["@/components/ui/button"],
    files: [{
      path: "./src/ui-registry/registry/examples/button-link.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/ui-registry/registry/examples/button-link.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-link"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["button"],
    meta: {},
  },
}