// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
	"jsx-renderer": {
		name: "jsx-renderer",
		description:
			"A component that renders JSX strings with access to tailwind, shadcn components and lucide icons.",
		type: "registry:ui",
		registryDependencies: ["@simple-ai/jsx-utils"],
		files: [
			{
				path: "./src/registry/ui/jsx-renderer.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/jsx-renderer.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input": {
		name: "chat-input",
		description:
			"A chat input component with mention support and automatic height adjustment.",
		type: "registry:ui",
		registryDependencies: ["input-group", "button"],
		files: [
			{
				path: "./src/registry/ui/chat-input.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-input.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area": {
		name: "chat-message-area",
		description:
			"A component that adds auto scrolling functionality to a list of messages.",
		type: "registry:ui",
		registryDependencies: ["button"],
		files: [
			{
				path: "./src/registry/ui/chat-message-area.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message-area.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message": {
		name: "chat-message",
		description:
			"A fully composable component for displaying chat messages with rich features like timestamps, actions, and threading.",
		type: "registry:ui",
		registryDependencies: [
			"@simple-ai/markdown-content",
			"avatar",
			"button",
			"card",
			"tooltip",
		],
		files: [
			{
				path: "./src/registry/ui/chat-message.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-suggestions": {
		name: "chat-suggestions",
		description:
			"A composable component for displaying chat prompt suggestions as clickable buttons.",
		type: "registry:ui",
		registryDependencies: ["button"],
		files: [
			{
				path: "./src/registry/ui/chat-suggestions.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-suggestions.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-content": {
		name: "markdown-content",
		description: "A component that renders markdown content.",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/markdown-content.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/markdown-content.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"tool-invocation": {
		name: "tool-invocation",
		description:
			"A component that displays a tool invocation with a collapsible content.",
		type: "registry:ui",
		registryDependencies: ["card", "collapsible"],
		files: [
			{
				path: "./src/registry/ui/tool-invocation.tsx",
				type: "registry:ui",
				target: "",
			},
			{
				path: "./src/registry/lib/id-to-readable-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/tool-invocation.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector": {
		name: "model-selector",
		description:
			"A dropdown component for selecting AI models with provider icons.",
		type: "registry:ui",
		registryDependencies: ["select"],
		files: [
			{
				path: "./src/registry/ui/model-selector.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/model-selector.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"resizable-node": {
		name: "resizable-node",
		description:
			"A wrapper React Flow node component that adds resizing functionality to other nodes.",
		type: "registry:ui",
		registryDependencies: ["@simple-ai/base-node"],
		files: [
			{
				path: "./src/registry/ui/flow/resizable-node.tsx",
				type: "registry:ui",
				target: "components/flow/resizable-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/resizable-node.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"node-header-status": {
		name: "node-header-status",
		description:
			"A React Flow component that displays status indicators in node headers.",
		type: "registry:ui",
		registryDependencies: ["badge"],
		files: [
			{
				path: "./src/registry/ui/flow/node-header-status.tsx",
				type: "registry:ui",
				target: "components/flow/node-header-status.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/node-header-status.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"editable-handle": {
		name: "editable-handle",
		description:
			"A React Flow component that allows you to dynamically add, edit, or remove input/output handles on your nodes.",
		type: "registry:ui",
		registryDependencies: [
			"button",
			"input",
			"textarea",
			"popover",
			"@simple-ai/base-handle",
		],
		files: [
			{
				path: "./src/registry/ui/flow/editable-handle.tsx",
				type: "registry:ui",
				target: "components/flow/editable-handle.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/editable-handle.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"status-edge": {
		name: "status-edge",
		description:
			"A React Flow edge component that provides visual feedback through color-coded states.",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/status-edge.tsx",
				type: "registry:ui",
				target: "components/flow/status-edge.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/status-edge.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"generate-text-node": {
		name: "generate-text-node",
		description:
			"A React Flow node component that represents Vercel AI SDK's text generation capabilities, featuring system instructions, prompts, and optional tool outputs.",
		type: "registry:ui",
		registryDependencies: [
			"button",
			"separator",
			"@simple-ai/model-selector",
			"@simple-ai/node-header-status",
			"@simple-ai/editable-handle",
			"@simple-ai/labeled-handle",
			"@simple-ai/base-node",
			"@simple-ai/node-header",
		],
		files: [
			{
				path: "./src/registry/ui/flow/generate-text-node.tsx",
				type: "registry:ui",
				target: "components/flow/generate-text-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/generate-text-node.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"prompt-crafter-node": {
		name: "prompt-crafter-node",
		description:
			"A React Flow node component for building dynamic prompts by combining multiple inputs using a template-based approach.",
		type: "registry:ui",
		registryDependencies: [
			"button",
			"separator",
			"popover",
			"command",
			"@simple-ai/node-header-status",
			"@simple-ai/editable-handle",
			"@simple-ai/node-header",
			"@simple-ai/labeled-handle",
			"@simple-ai/base-node",
		],
		files: [
			{
				path: "./src/registry/ui/flow/prompt-crafter-node.tsx",
				type: "registry:ui",
				target: "components/flow/prompt-crafter-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/prompt-crafter-node.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"text-input-node": {
		name: "text-input-node",
		description:
			"A React Flow node component that provides a simple text input interface with a resizable textarea and single output.",
		type: "registry:ui",
		registryDependencies: [
			"textarea",
			"separator",
			"@simple-ai/labeled-handle",
			"@simple-ai/node-header",
			"@simple-ai/resizable-node",
		],
		files: [
			{
				path: "./src/registry/ui/flow/text-input-node.tsx",
				type: "registry:ui",
				target: "components/flow/text-input-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/text-input-node.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"visualize-text-node": {
		name: "visualize-text-node",
		description:
			"A React Flow node component for displaying text content with Markdown support and a resizable interface.",
		type: "registry:ui",
		registryDependencies: [
			"separator",
			"@simple-ai/markdown-content",
			"@simple-ai/labeled-handle",
			"@simple-ai/node-header",
			"@simple-ai/resizable-node",
		],
		files: [
			{
				path: "./src/registry/ui/flow/visualize-text-node.tsx",
				type: "registry:ui",
				target: "components/flow/visualize-text-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/visualize-text-node.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"base-handle": {
		name: "base-handle",
		description: "",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/base-handle.tsx",
				type: "registry:ui",
				target: "components/flow/base-handle.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/base-handle.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"labeled-handle": {
		name: "labeled-handle",
		description: "",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/labeled-handle.tsx",
				type: "registry:ui",
				target: "components/flow/labeled-handle.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/labeled-handle.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"base-node": {
		name: "base-node",
		description: "",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/base-node.tsx",
				type: "registry:ui",
				target: "components/flow/base-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/base-node.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"node-header": {
		name: "node-header",
		description: "",
		type: "registry:ui",
		registryDependencies: ["button", "dropdown-menu"],
		files: [
			{
				path: "./src/registry/ui/flow/node-header.tsx",
				type: "registry:ui",
				target: "components/flow/node-header.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/node-header.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"json-schema-editor": {
		name: "json-schema-editor",
		description:
			"A visual editor for creating and editing JSON Schema definitions with support for nested objects, arrays, enums, and property descriptions.",
		type: "registry:ui",
		registryDependencies: ["button", "dialog", "input", "select"],
		files: [
			{
				path: "./src/registry/ui/json-schema-editor.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/json-schema-editor.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"json-schema-viewer": {
		name: "json-schema-viewer",
		description:
			"A read-only component for displaying JSON Schema structures with support for union types, nested objects, arrays, and enums.",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/json-schema-viewer.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/json-schema-viewer.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	reasoning: {
		name: "reasoning",
		description:
			"A component for displaying AI reasoning content with collapsible sections and streaming support.",
		type: "registry:ui",
		registryDependencies: ["collapsible", "@simple-ai/markdown-content"],
		files: [
			{
				path: "./src/registry/ui/reasoning.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/reasoning.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"use-textarea-resize": {
		name: "use-textarea-resize",
		description: "",
		type: "registry:hook",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/hooks/use-textarea-resize.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/hooks/use-textarea-resize.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-utils": {
		name: "jsx-utils",
		description: "A set of utilities for working with JSX.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/lib/jsx-utils.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/lib/jsx-utils.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"id-to-readable-text": {
		name: "id-to-readable-text",
		description: "A utility for converting an ID to a readable text.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/lib/id-to-readable-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/lib/id-to-readable-text.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-demo-mentions": {
		name: "chat-input-demo-mentions",
		description: "",
		type: "registry:example",
		registryDependencies: ["@simple-ai/chat-input"],
		files: [
			{
				path: "./src/registry/examples/chat-input-demo-mentions.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-demo-mentions.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-with-addons": {
		name: "chat-input-with-addons",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-input-with-addons.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-with-addons.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-demo-simple": {
		name: "chat-input-demo-simple",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-input-demo-simple.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-demo-simple.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-content-demo": {
		name: "markdown-content-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/markdown-content-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/markdown-content-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-streaming-demo": {
		name: "markdown-streaming-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/markdown-streaming-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/markdown-streaming-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo": {
		name: "chat-message-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-simple": {
		name: "chat-message-demo-simple",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-simple.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-simple.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-avatar-image": {
		name: "chat-message-demo-avatar-image",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-avatar-image.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-avatar-image.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo": {
		name: "chat-message-area-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo-alignment": {
		name: "chat-message-area-demo-alignment",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo-alignment.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo-alignment.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo-streaming": {
		name: "chat-message-area-demo-streaming",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo-streaming.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo-streaming.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer-demo": {
		name: "jsx-renderer-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["@simple-ai/jsx-renderer"],
		files: [
			{
				path: "./src/registry/examples/jsx-renderer-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/jsx-renderer-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer-disabled-demo": {
		name: "jsx-renderer-disabled-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["@simple-ai/jsx-renderer"],
		files: [
			{
				path: "./src/registry/examples/jsx-renderer-disabled-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/jsx-renderer-disabled-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer-streaming-demo": {
		name: "jsx-renderer-streaming-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["@simple-ai/jsx-renderer"],
		files: [
			{
				path: "./src/registry/examples/jsx-renderer-streaming-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/jsx-renderer-streaming-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector-demo": {
		name: "model-selector-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/model-selector-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/model-selector-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector-disabled-demo": {
		name: "model-selector-disabled-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/model-selector-disabled-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/model-selector-disabled-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"resizable-node-demo": {
		name: "resizable-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/resizable-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/resizable-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"visualize-text-node-demo": {
		name: "visualize-text-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/visualize-text-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/visualize-text-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"prompt-crafter-node-demo": {
		name: "prompt-crafter-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/prompt-crafter-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/prompt-crafter-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"text-input-node-demo": {
		name: "text-input-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/text-input-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/text-input-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"generate-text-node-demo": {
		name: "generate-text-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/generate-text-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/generate-text-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"editable-handle-demo": {
		name: "editable-handle-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/editable-handle-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/editable-handle-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"status-edge-demo": {
		name: "status-edge-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/status-edge-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/status-edge-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"tool-invocation-demo": {
		name: "tool-invocation-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/tool-invocation-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/tool-invocation-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"tool-invocation-demo-loading": {
		name: "tool-invocation-demo-loading",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/tool-invocation-demo-loading.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/tool-invocation-demo-loading.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"tool-invocation-demo-error": {
		name: "tool-invocation-demo-error",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/tool-invocation-demo-error.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/tool-invocation-demo-error.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-suggestions-demo": {
		name: "chat-suggestions-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-suggestions-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-suggestions-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-suggestions-demo-simple": {
		name: "chat-suggestions-demo-simple",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-suggestions-demo-simple.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-suggestions-demo-simple.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-01": {
		name: "chat-01",
		description: "A simple chat page.",
		type: "registry:block",
		registryDependencies: [
			"card",
			"breadcrumb",
			"separator",
			"sidebar",
			"tooltip",
			"button",
			"avatar",
			"dropdown-menu",
			"@simple-ai/chat-input",
			"@simple-ai/chat-message-area",
			"@simple-ai/chat-message",
			"@simple-ai/tool-invocation",
			"@simple-ai/chat-suggestions",
			"@simple-ai/reasoning",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-01/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-01/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-01/lib/config.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/lib/tools.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/lib/messages.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/types/ai-messages.ts",
				type: "registry:lib",
				target: "types/ai-messages.ts",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-layout.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-layout-skeleton.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-header.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-sidebar.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-main-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-secondary-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-user-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/chat/chat-main.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/chat/chat-header.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/chat/chat-content.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-01/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
	"chat-04": {
		name: "chat-04",
		description: "A chat with multiple agents support.",
		type: "registry:block",
		registryDependencies: [
			"card",
			"badge",
			"breadcrumb",
			"separator",
			"sidebar",
			"tooltip",
			"button",
			"avatar",
			"dropdown-menu",
			"@simple-ai/chat-input",
			"@simple-ai/chat-message-area",
			"@simple-ai/chat-message",
			"@simple-ai/tool-invocation",
			"@simple-ai/chat-suggestions",
			"@simple-ai/reasoning",
			"@simple-ai/agents",
			"@simple-ai/messages",
			"@simple-ai/models",
			"@simple-ai/tools",
			"@simple-ai/agent-respond",
			"@simple-ai/ai-utils",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-04/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-04/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-04/lib/config.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/layout/app-layout.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/layout/app-layout-skeleton.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/layout/app-header.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/layout/app-sidebar.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/layout/app-main-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/layout/app-secondary-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/layout/app-user-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/chat/chat-main.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/chat/chat-header.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-04/components/chat/chat-content.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-04/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
	"chat-02": {
		name: "chat-02",
		description: "A chat in a sidebar.",
		type: "registry:block",
		registryDependencies: [
			"sidebar",
			"breadcrumb",
			"@simple-ai/chat-input",
			"@simple-ai/chat-message-area",
			"@simple-ai/chat-message",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-02/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-02/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-02/components/app-sidebar.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-02/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
	"chat-03": {
		name: "chat-03",
		description: "A chat in a popover.",
		type: "registry:block",
		registryDependencies: [
			"popover",
			"button",
			"@simple-ai/chat-input",
			"@simple-ai/chat-message-area",
			"@simple-ai/chat-message",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-03/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-03/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-03/components/chat.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-03/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
	"app-01": {
		name: "app-01",
		description: "A app with generative UI capabilities.",
		type: "registry:block",
		registryDependencies: [
			"avatar",
			"input",
			"label",
			"tabs",
			"resizable",
			"breadcrumb",
			"button",
			"toggle-group",
			"switch",
			"separator",
			"card",
			"badge",
			"dialog",
			"slider",
			"@simple-ai/chat-input",
			"@simple-ai/chat-message-area",
			"@simple-ai/chat-message",
			"@simple-ai/jsx-renderer",
			"@simple-ai/jsx-utils",
		],
		files: [
			{
				path: "./src/registry/blocks/app-01/page.tsx",
				type: "registry:page",
				target: "app/generative-ui/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-01/canvas/page.tsx",
				type: "registry:page",
				target: "app/canvas/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-01/route.ts",
				type: "registry:page",
				target: "app/api/ai/generate/route.ts",
			},
			{
				path: "./src/registry/blocks/app-01/hooks/generation-store.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/versions.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/editor-layout.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/editor-toolbar.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/code-editor.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/preview.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/chat-dialog.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/copy-button.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/app-01/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["app"],
		meta: undefined,
	},
	"app-02": {
		name: "app-02",
		description: "A persona generator app with structured outputs.",
		type: "registry:block",
		registryDependencies: [
			"dialog",
			"button",
			"input",
			"textarea",
			"label",
			"scroll-area",
			"form",
			"skeleton",
			"card",
			"avatar",
		],
		files: [
			{
				path: "./src/registry/blocks/app-02/page.tsx",
				type: "registry:page",
				target: "app/persona/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-02/route.ts",
				type: "registry:page",
				target: "app/api/ai/persona/route.ts",
			},
			{
				path: "./src/registry/blocks/app-02/components/persona-display.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-02/lib/persona.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-02/lib/example-businesses.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/app-02/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["app"],
		meta: undefined,
	},
	"app-03": {
		name: "app-03",
		description: "An X profile bio generator app.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"dialog",
			"input",
			"textarea",
			"form",
			"label",
			"select",
			"skeleton",
			"avatar",
		],
		files: [
			{
				path: "./src/registry/blocks/app-03/page.tsx",
				type: "registry:page",
				target: "app/x-profile/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-03/layout.tsx",
				type: "registry:page",
				target: "app/x-profile/layout.tsx",
			},
			{
				path: "./src/registry/blocks/app-03/route.ts",
				type: "registry:page",
				target: "app/api/ai/x-profile/route.ts",
			},
			{
				path: "./src/registry/blocks/app-03/components/profile-generate-dialog.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/components/x-preview.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/components/toolbar.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/components/theme-toggle.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/lib/x.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/lib/profile-examples.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/app-03/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["app"],
		meta: undefined,
	},
	"flow-chain": {
		name: "flow-chain",
		description: "Agentic chain workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"@simple-ai/generate-text-node",
			"@simple-ai/prompt-crafter-node",
			"@simple-ai/text-input-node",
			"@simple-ai/visualize-text-node",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-chain/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-chain/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-chain/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-chain/components/error-indicator.tsx",
				type: "registry:component",
				target: "components/error-indicator.tsx",
			},
			{
				path: "./src/registry/blocks/flow-chain/lib/news-summarization-chain.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/status-edge.tsx",
				type: "registry:component",
				target: "components/flow/status-edge.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/flow-chain/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
	"flow-routing": {
		name: "flow-routing",
		description: "Agentic routing workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"@simple-ai/generate-text-node",
			"@simple-ai/prompt-crafter-node",
			"@simple-ai/text-input-node",
			"@simple-ai/visualize-text-node",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-routing/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-routing/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-routing/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-chain/components/error-indicator.tsx",
				type: "registry:component",
				target: "components/error-indicator.tsx",
			},
			{
				path: "./src/registry/blocks/flow-routing/lib/content-creator-routing.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/status-edge.tsx",
				type: "registry:component",
				target: "components/flow/status-edge.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/flow-routing/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
	"flow-parallelization": {
		name: "flow-parallelization",
		description: "Agentic parallelization workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"@simple-ai/generate-text-node",
			"@simple-ai/prompt-crafter-node",
			"@simple-ai/text-input-node",
			"@simple-ai/visualize-text-node",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-parallelization/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-parallelization/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-parallelization/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-parallelization/components/error-indicator.tsx",
				type: "registry:component",
				target: "components/error-indicator.tsx",
			},
			{
				path: "./src/registry/blocks/flow-parallelization/lib/exam-creator-parallelization.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/status-edge.tsx",
				type: "registry:component",
				target: "components/flow/status-edge.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/blocks/flow-parallelization/page.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
	"flow-orchestrator": {
		name: "flow-orchestrator",
		description: "Agentic orchestrator workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"@simple-ai/generate-text-node",
			"@simple-ai/prompt-crafter-node",
			"@simple-ai/text-input-node",
			"@simple-ai/visualize-text-node",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-orchestrator/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-orchestrator/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-orchestrator/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-orchestrator/components/error-indicator.tsx",
				type: "registry:component",
				target: "components/error-indicator.tsx",
			},
			{
				path: "./src/registry/blocks/flow-orchestrator/lib/developer-tasks-orchestrator.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/status-edge.tsx",
				type: "registry:component",
				target: "components/flow/status-edge.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/blocks/flow-orchestrator/page.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
	"workflow-01": {
		name: "workflow-01",
		description: "Build powerful AI agent workflows",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"sidebar",
			"badge",
			"checkbox",
			"collapsible",
			"dropdown-menu",
			"popover",
			"select",
			"switch",
			"tooltip",
			"separator",
			"@simple-ai/chat-input",
			"@simple-ai/chat-message-area",
			"@simple-ai/chat-message",
			"@simple-ai/tool-invocation",
			"@simple-ai/chat-suggestions",
			"@simple-ai/reasoning",
			"@simple-ai/json-schema-editor",
		],
		files: [
			{
				path: "./src/registry/blocks/workflow-01/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/route.ts",
				type: "registry:page",
				target: "app/api/workflow/route.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/app-header.tsx",
				type: "registry:component",
				target: "components/app-header.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/app-layout.tsx",
				type: "registry:component",
				target: "components/app-layout.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/chat.tsx",
				type: "registry:component",
				target: "components/chat.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/editor/condition-editor.tsx",
				type: "registry:component",
				target: "components/editor/condition-editor.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/editor/condition-editor.css",
				type: "registry:style",
				target: "components/editor/condition-editor.css",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/node-editor-panel.tsx",
				type: "registry:component",
				target: "components/node-editor-panel.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/node-execution.tsx",
				type: "registry:component",
				target: "components/node-execution.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/node-selector-panel.tsx",
				type: "registry:component",
				target: "components/node-selector-panel.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/template-selector.tsx",
				type: "registry:component",
				target: "components/template-selector.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/theme-provider.tsx",
				type: "registry:component",
				target: "components/theme-provider.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/theme-toggle.tsx",
				type: "registry:component",
				target: "components/theme-toggle.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/validation-status.tsx",
				type: "registry:component",
				target: "components/validation-status.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/index.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/agent/agent.shared.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/agent/agent.shared.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/agent/agent.client.tsx",
				type: "registry:component",
				target: "lib/workflow/nodes/agent/agent.client.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/agent/agent.server.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/agent/agent.server.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/agent/index.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/agent/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/if-else/if-else.shared.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/if-else/if-else.shared.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/if-else/if-else.client.tsx",
				type: "registry:component",
				target: "lib/workflow/nodes/if-else/if-else.client.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/if-else/if-else.server.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/if-else/if-else.server.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/if-else/index.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/if-else/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/start/start.shared.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/start/start.shared.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/start/start.client.tsx",
				type: "registry:component",
				target: "lib/workflow/nodes/start/start.client.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/start/start.server.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/start/start.server.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/start/index.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/start/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/end/end.shared.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/end/end.shared.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/end/end.client.tsx",
				type: "registry:component",
				target: "lib/workflow/nodes/end/end.client.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/end/end.server.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/end/end.server.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/end/index.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/end/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/note/note.shared.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/note/note.shared.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/note/note.client.tsx",
				type: "registry:component",
				target: "lib/workflow/nodes/note/note.client.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/note/note.server.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/note/note.server.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/note/index.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/note/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/wait/wait.shared.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/wait/wait.shared.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/wait/wait.client.tsx",
				type: "registry:component",
				target: "lib/workflow/nodes/wait/wait.client.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/wait/wait.server.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/wait/wait.server.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/nodes/wait/index.ts",
				type: "registry:lib",
				target: "lib/workflow/nodes/wait/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/workflow/primitives/base-handle.tsx",
				type: "registry:component",
				target: "components/workflow/primitives/base-handle.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/workflow/primitives/base-node.tsx",
				type: "registry:component",
				target: "components/workflow/primitives/base-node.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/workflow/primitives/labeled-handle.tsx",
				type: "registry:component",
				target: "components/workflow/primitives/labeled-handle.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/workflow/primitives/node-header.tsx",
				type: "registry:component",
				target: "components/workflow/primitives/node-header.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/workflow/primitives/resizable-node.tsx",
				type: "registry:component",
				target: "components/workflow/primitives/resizable-node.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/workflow/status-edge.tsx",
				type: "registry:component",
				target: "components/workflow/status-edge.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/components/model-selector.tsx",
				type: "registry:component",
				target: "components/model-selector.tsx",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/templates/index.ts",
				type: "registry:lib",
				target: "lib/templates/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/templates/code-analysis-workflow.ts",
				type: "registry:lib",
				target: "lib/templates/code-analysis-workflow.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/templates/wikipedia-research-workflow.ts",
				type: "registry:lib",
				target: "lib/templates/wikipedia-research-workflow.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/templates/wait-demo-workflow.ts",
				type: "registry:lib",
				target: "lib/templates/wait-demo-workflow.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/templates/customer-support-workflow.ts",
				type: "registry:lib",
				target: "lib/templates/customer-support-workflow.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/tools/index.ts",
				type: "registry:lib",
				target: "lib/tools/index.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/tools/wikipedia-query.ts",
				type: "registry:lib",
				target: "lib/tools/wikipedia-query.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/executor.ts",
				type: "registry:lib",
				target: "lib/workflow/executor.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/models-external.ts",
				type: "registry:lib",
				target: "lib/workflow/models.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/types/messages.ts",
				type: "registry:lib",
				target: "types/messages.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/types/workflow.ts",
				type: "registry:lib",
				target: "types/workflow.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/validation.ts",
				type: "registry:lib",
				target: "lib/workflow/validation.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/context/schema-introspection.ts",
				type: "registry:lib",
				target: "lib/workflow/context/schema-introspection.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/lib/workflow/context/variable-resolver.ts",
				type: "registry:lib",
				target: "lib/workflow/context/variable-resolver.ts",
			},
			{
				path: "./src/registry/blocks/workflow-01/hooks/use-workflow.ts",
				type: "registry:hook",
				target: "hooks/workflow/use-workflow.ts",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/workflow-01/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["workflow"],
		meta: undefined,
	},
	agents: {
		name: "agents",
		description: "A set of default agents.",
		type: "registry:lib",
		registryDependencies: [
			"@simple-ai/models",
			"@simple-ai/weather-agent",
			"@simple-ai/exa-agent",
			"@simple-ai/firecrawl-agent",
			"@simple-ai/id-to-readable-text",
		],
		files: [
			{
				path: "./src/registry/ai/agents/agents.ts",
				type: "registry:lib",
				target: "lib/ai/agents.ts",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/agents/agents.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"weather-agent": {
		name: "weather-agent",
		description: "A weather agent with tools for getting the weather.",
		type: "registry:lib",
		registryDependencies: ["@simple-ai/models", "@simple-ai/get-weather"],
		files: [
			{
				path: "./src/registry/ai/agents/weather-agent.ts",
				type: "registry:lib",
				target: "lib/ai/agents/weather-agent.ts",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/agents/weather-agent.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["agent"],
		meta: {
			icon: "CloudRain",
			toolIds: ["get-weather"],
			suggestions: [
				"What's the weather like in New York today?",
				"Will it rain in London tomorrow?",
				"What's the forecast for Tokyo next week?",
				"How's the weather in Paris right now?",
			],
			prompt: "You are a helpful weather assistant. Your role is to provide accurate and helpful weather information to users.\n\nWhen users ask about weather:\n- Use the get-weather tool to retrieve current weather conditions\n- Always specify the city and preferred temperature unit (fahrenheit or celsius)\n- Provide clear, concise weather information\n- If a user doesn't specify a unit, default to fahrenheit\n- Be friendly and helpful in your responses",
		},
	},
	"firecrawl-agent": {
		name: "firecrawl-agent",
		description: "A web research agent powered by Firecrawl.",
		type: "registry:lib",
		registryDependencies: [
			"@simple-ai/models",
			"@simple-ai/firecrawl-tool",
		],
		files: [
			{
				path: "./src/registry/ai/agents/firecrawl-agent.ts",
				type: "registry:lib",
				target: "lib/ai/agents/firecrawl-agent.ts",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/agents/firecrawl-agent.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["agent"],
		meta: {
			icon: "FirecrawlIcon",
			toolIds: ["firecrawl-tool"],
			suggestions: [
				"Scrape https://example.com",
				"Search for recent news about AI agents",
				"Find documentation for the Vercel AI SDK",
				"Get content from a specific URL",
			],
			prompt: "You are a web research assistant powered by Firecrawl.\nYour goal is to find accurate information from the web efficiently.\n\nInstructions:\n- If the user provides a specific URL, use the 'scrape' mode to get the content.\n- If the user asks a general question, use the 'search' mode to find relevant pages.\n- The tool returns Markdown content. Summarize this content clearly for the user.\n- Cite the URLs you found information from.",
		},
	},
	"exa-agent": {
		name: "exa-agent",
		description: "A web research agent powered by Exa.",
		type: "registry:lib",
		registryDependencies: ["@simple-ai/models", "@simple-ai/exa-tool"],
		files: [
			{
				path: "./src/registry/ai/agents/exa-agent.ts",
				type: "registry:lib",
				target: "lib/ai/agents/exa-agent.ts",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/agents/exa-agent.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["agent"],
		meta: {
			icon: "ExaIcon",
			toolIds: ["exa-tool"],
			suggestions: [
				"Find similar companies to https://exa.ai",
				"Research the latest trends in generative AI",
				"Retrieve content from https://example.com",
				"Find blog posts about Rust programming",
			],
			prompt: "You are a highly capable web research assistant powered by Exa.\nYour goal is to find, verify, and synthesize information from the web.\n\nInstructions:\n- Use 'search' mode for general queries to find relevant pages and their content.\n- Use 'retrieve' mode if the user provides a specific URL that needs to be read.\n- Use 'find-similar' mode if the user wants to find websites related to a specific URL.\n- Exa provides clean Markdown content. Use this to summarize answers effectively.\n- Always cite the source URLs provided in the search results.",
		},
	},
	tools: {
		name: "tools",
		description: "A set of tools for the AI SDK.",
		type: "registry:lib",
		registryDependencies: [
			"@simple-ai/exa-tool",
			"@simple-ai/firecrawl-tool",
			"@simple-ai/get-weather",
		],
		files: [
			{
				path: "./src/registry/ai/tools/tools.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/tools/tools.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"get-weather": {
		name: "get-weather",
		description: "A tool for getting the weather.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ai/tools/get-weather.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/tools/get-weather.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"firecrawl-tool": {
		name: "firecrawl-tool",
		description:
			"A tool for searching and scraping the web using Firecrawl.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ai/tools/firecrawl-tool.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/tools/firecrawl-tool.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"exa-tool": {
		name: "exa-tool",
		description: "A tool for searching and scraping the web using Exa.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ai/tools/exa-tool.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/tools/exa-tool.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"agent-respond": {
		name: "agent-respond",
		description: "A function to respond to a message with an agent.",
		type: "registry:lib",
		registryDependencies: ["@simple-ai/id-to-readable-text"],
		files: [
			{
				path: "./src/registry/ai/agent-route-respond.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/agent-route-respond.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	models: {
		name: "models",
		description: "A set of models for the AI SDK.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ai/models.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/models.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	messages: {
		name: "messages",
		description: "UIMessage types for the AI SDK.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ai/messages.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/messages.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"ai-utils": {
		name: "ai-utils",
		description: "A set of utilities for the AI SDK.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ai/ai-utils.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ai/ai-utils.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
};
