// AUTO-GENERATED by `pnpm --filter @workspace/registry generate`. Do not edit by hand.
import { lazy } from "react";
import type { RegistryEntry } from "./types";

export const REGISTRY: Record<string, RegistryEntry> = {
  "chat-page": {
    name: "chat-page",
    type: "registry:block",
    title: "Chat page",
    description: "Full-screen chat with tools, files, and mentions.",
    meta: { iframeHeight: 900 },
    component: lazy(() => import("../registry/blocks/chat-page/page")),
  },
  composer: {
    name: "composer",
    type: "registry:ui",
    title: "Composer",
    description: "TipTap composer with mentions and streaming status.",
    meta: {},
    component: lazy(() => import("../registry/components/composer/preview")),
  },
  reasoning: {
    name: "reasoning",
    type: "registry:ui",
    title: "Reasoning",
    description: "Collapsible thinking with duration and markdown.",
    meta: {},
    component: lazy(() => import("../registry/components/reasoning/preview")),
  },
  shell: {
    name: "shell",
    type: "registry:ui",
    title: "Shell",
    description: "Sidebar, header, and main content.",
    meta: { fullBleed: true, iframeHeight: 720 },
    component: lazy(() => import("../registry/components/shell/preview")),
  },
  tool: {
    name: "tool",
    type: "registry:ui",
    title: "Tool",
    description: "Tool call with status, params, and output.",
    meta: {},
    component: lazy(() => import("../registry/components/tool/preview")),
  },
};
