// AUTO-GENERATED by `pnpm --filter @workspace/registry generate`. Do not edit by hand.
import { lazy } from "react";
import type { RegistryEntry } from "./types";

export const REGISTRY: Record<string, RegistryEntry> = {
  "chat-card": {
    name: "chat-card",
    type: "registry:block",
    title: "Chat card",
    description: "In-world chat for React Three Fiber and WebXR.",
    meta: { iframeHeight: 720, fullBleed: true },
    component: lazy(() => import("../registry/blocks/chat-card/page")),
  },
  "chat-input": {
    name: "chat-input",
    type: "registry:ui",
    title: "Chat input",
    description: "Chat input with mentions and streaming status.",
    meta: {},
    component: lazy(() => import("../registry/examples/chat-input-demo")),
  },
  "chat-page": {
    name: "chat-page",
    type: "registry:block",
    title: "Chat page",
    description: "Full-screen chat with tools, files, and mentions.",
    meta: { iframeHeight: 900 },
    component: lazy(() => import("../registry/blocks/chat-page/page")),
  },
  reasoning: {
    name: "reasoning",
    type: "registry:ui",
    title: "Reasoning",
    description: "Quiet thinking row with markdown.",
    meta: {},
    component: lazy(() => import("../registry/examples/reasoning-demo")),
  },
  shell: {
    name: "shell",
    type: "registry:ui",
    title: "Shell",
    description: "Sidebar, header, and main content.",
    meta: { fullBleed: true, iframeHeight: 720 },
    component: lazy(() => import("../registry/examples/shell-demo")),
  },
  tool: {
    name: "tool",
    type: "registry:ui",
    title: "Tool",
    description: "Quiet collapsible tool call with input and output.",
    meta: {},
    component: lazy(() => import("../registry/examples/tool-demo")),
  },
  worked: {
    name: "worked",
    type: "registry:ui",
    title: "Worked",
    description: "Fold the agent's work. Keep the answer.",
    meta: {},
    component: lazy(() => import("../registry/examples/worked-demo")),
  },
  "world-card": {
    name: "world-card",
    type: "registry:ui",
    title: "World card",
    description: "Spatial chrome for in-world cards in React Three Fiber.",
    meta: {},
    component: lazy(() => import("../registry/examples/world-card-demo")),
  },
};
