// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
	"chat-input": {
		name: "chat-input",
		description: "",
		type: "registry:ui",
		registryDependencies: ["textarea"],
		files: [
			{
				path: "./src/registry/ui/chat-input.tsx",
				type: "registry:ui",
				target: "",
			},
			{
				path: "./src/registry/hooks/use-textarea-resize.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-input.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message": {
		name: "chat-message",
		description: "",
		type: "registry:ui",
		registryDependencies: [],
		files: [
			{
				path: "./src/registry/ui/chat-message.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area": {
		name: "chat-message-area",
		description: "",
		type: "registry:ui",
		registryDependencies: ["scroll-area"],
		files: [
			{
				path: "./src/registry/ui/chat-message-area.tsx",
				type: "registry:ui",
				target: "",
			},
			{
				path: "./src/registry/hooks/use-scroll-to-bottom.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message-area.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-content": {
		name: "markdown-content",
		description: "",
		type: "registry:ui",
		registryDependencies: [],
		files: [
			{
				path: "./src/registry/ui/markdown-content.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/markdown-content.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer": {
		name: "jsx-renderer",
		description:
			"A component that renders JSX strings with access to tailwind, shadcn components and lucide icons.",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/jsx-renderer.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/jsx-renderer.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector": {
		name: "model-selector",
		description: "",
		type: "registry:ui",
		registryDependencies: ["select"],
		files: [
			{
				path: "./src/registry/ui/model-selector.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/model-selector.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"use-textarea-resize": {
		name: "use-textarea-resize",
		description: "",
		type: "registry:hook",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/hooks/use-textarea-resize.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/hooks/use-textarea-resize.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"use-scroll-to-bottom": {
		name: "use-scroll-to-bottom",
		description: "",
		type: "registry:hook",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/hooks/use-scroll-to-bottom.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/hooks/use-scroll-to-bottom.ts"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-utils": {
		name: "jsx-utils",
		description: "",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/lib/jsx-utils.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/lib/jsx-utils.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-demo": {
		name: "chat-input-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["undefined/r/chat-input.json"],
		files: [
			{
				path: "./src/registry/examples/chat-input-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/examples/chat-input-demo.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-unstyled": {
		name: "chat-input-unstyled",
		description: "",
		type: "registry:example",
		registryDependencies: ["undefined/r/chat-input.json"],
		files: [
			{
				path: "./src/registry/examples/chat-input-unstyled.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-unstyled.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-unstyled-initial-rows": {
		name: "chat-input-unstyled-initial-rows",
		description: "",
		type: "registry:example",
		registryDependencies: ["undefined/r/chat-input.json"],
		files: [
			{
				path: "./src/registry/examples/chat-input-unstyled-initial-rows.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-unstyled-initial-rows.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo": {
		name: "chat-message-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-default": {
		name: "chat-message-demo-default",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-default.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-default.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-bubble": {
		name: "chat-message-demo-bubble",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-bubble.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-bubble.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-full": {
		name: "chat-message-demo-full",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-full.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-full.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-without-avatar": {
		name: "chat-message-demo-without-avatar",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-without-avatar.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-without-avatar.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-avatar-image": {
		name: "chat-message-demo-avatar-image",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-avatar-image.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-avatar-image.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-markdown-content": {
		name: "chat-message-demo-markdown-content",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-markdown-content.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-markdown-content.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo": {
		name: "chat-message-area-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo-alignment": {
		name: "chat-message-area-demo-alignment",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo-alignment.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo-alignment.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo-streaming": {
		name: "chat-message-area-demo-streaming",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo-streaming.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo-streaming.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-content-demo": {
		name: "markdown-content-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/markdown-content-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/markdown-content-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-streaming-demo": {
		name: "markdown-streaming-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/markdown-streaming-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/markdown-streaming-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer-demo": {
		name: "jsx-renderer-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["undefined/r/jsx-renderer.json"],
		files: [
			{
				path: "./src/registry/examples/jsx-renderer-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/jsx-renderer-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector-demo": {
		name: "model-selector-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["undefined/r/model-selector.json"],
		files: [
			{
				path: "./src/registry/examples/model-selector-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/model-selector-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-01": {
		name: "chat-01",
		description: "A simple chat page.",
		type: "registry:block",
		registryDependencies: [
			"card",
			"breadcrumb",
			"separator",
			"sidebar",
			"tooltip",
			"button",
			"avatar",
			"dropdown-menu",
			"undefined/r/chat-input.json",
			"undefined/r/chat-message-area.json",
			"undefined/r/chat-message.json",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-01/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-01/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-01/components/chat.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/sidebar-app.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/nav-user.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-01/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
};
