// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
	"chat-input": {
		name: "chat-input",
		description: "",
		type: "registry:ui",
		registryDependencies: ["textarea"],
		files: [
			{
				path: "./src/registry/ui/chat-input.tsx",
				type: "registry:ui",
				target: "",
			},
			{
				path: "./src/registry/hooks/use-textarea-resize.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-input.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message": {
		name: "chat-message",
		description: "",
		type: "registry:ui",
		registryDependencies: [],
		files: [
			{
				path: "./src/registry/ui/chat-message.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area": {
		name: "chat-message-area",
		description: "",
		type: "registry:ui",
		registryDependencies: ["scroll-area"],
		files: [
			{
				path: "./src/registry/ui/chat-message-area.tsx",
				type: "registry:ui",
				target: "",
			},
			{
				path: "./src/registry/hooks/use-scroll-to-bottom.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message-area.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-content": {
		name: "markdown-content",
		description: "",
		type: "registry:ui",
		registryDependencies: [],
		files: [
			{
				path: "./src/registry/ui/markdown-content.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/markdown-content.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"use-textarea-resize": {
		name: "use-textarea-resize",
		description: "",
		type: "registry:hook",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/hooks/use-textarea-resize.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/hooks/use-textarea-resize.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"use-scroll-to-bottom": {
		name: "use-scroll-to-bottom",
		description: "",
		type: "registry:hook",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/hooks/use-scroll-to-bottom.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/hooks/use-scroll-to-bottom.ts"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-demo": {
		name: "chat-input-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["undefined/r/chat-input.json"],
		files: [
			{
				path: "./src/registry/examples/chat-input-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/examples/chat-input-demo.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
};
