// @ts-nocheck
/** biome-ignore-all lint/suspicious/noExplicitAny: Needed */
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
	"jsx-renderer": {
		name: "jsx-renderer",
		description:
			"A component that renders JSX strings with access to tailwind, shadcn components and lucide icons.",
		type: "registry:ui",
		registryDependencies: ["http://localhost:4567/r/jsx-utils.json"],
		files: [
			{
				path: "./src/registry/ui/jsx-renderer.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/jsx-renderer.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input": {
		name: "chat-input",
		description: "",
		type: "registry:ui",
		registryDependencies: ["input-group", "button"],
		files: [
			{
				path: "./src/registry/ui/chat-input.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-input.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area": {
		name: "chat-message-area",
		description: "",
		type: "registry:ui",
		registryDependencies: ["button"],
		files: [
			{
				path: "./src/registry/ui/chat-message-area.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message-area.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message": {
		name: "chat-message",
		description: "",
		type: "registry:ui",
		registryDependencies: [
			"http://localhost:4567/r/markdown-content.json",
			"avatar",
			"button",
			"card",
			"tooltip",
		],
		files: [
			{
				path: "./src/registry/ui/chat-message.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/chat-message.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-content": {
		name: "markdown-content",
		description: "A markdown content component.",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/markdown-content.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/markdown-content.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector": {
		name: "model-selector",
		description: "",
		type: "registry:ui",
		registryDependencies: ["select"],
		files: [
			{
				path: "./src/registry/ui/model-selector.tsx",
				type: "registry:ui",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/model-selector.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"resizable-node": {
		name: "resizable-node",
		description: "",
		type: "registry:ui",
		registryDependencies: ["http://localhost:4567/r/base-node.json"],
		files: [
			{
				path: "./src/registry/ui/flow/resizable-node.tsx",
				type: "registry:ui",
				target: "components/flow/resizable-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/resizable-node.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"node-header-status": {
		name: "node-header-status",
		description: "",
		type: "registry:ui",
		registryDependencies: ["badge"],
		files: [
			{
				path: "./src/registry/ui/flow/node-header-status.tsx",
				type: "registry:ui",
				target: "components/flow/node-header-status.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/node-header-status.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"editable-handle": {
		name: "editable-handle",
		description: "",
		type: "registry:ui",
		registryDependencies: [
			"button",
			"input",
			"textarea",
			"popover",
			"http://localhost:4567/r/base-handle.json",
		],
		files: [
			{
				path: "./src/registry/ui/flow/editable-handle.tsx",
				type: "registry:ui",
				target: "components/flow/editable-handle.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/editable-handle.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"status-edge": {
		name: "status-edge",
		description: "",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/status-edge.tsx",
				type: "registry:ui",
				target: "components/flow/status-edge.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/status-edge.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"generate-text-node": {
		name: "generate-text-node",
		description: "",
		type: "registry:ui",
		registryDependencies: [
			"button",
			"separator",
			"http://localhost:4567/r/model-selector.json",
			"http://localhost:4567/r/node-header-status.json",
			"http://localhost:4567/r/editable-handle.json",
			"http://localhost:4567/r/labeled-handle.json",
			"http://localhost:4567/r/base-node.json",
			"http://localhost:4567/r/node-header.json",
		],
		files: [
			{
				path: "./src/registry/ui/flow/generate-text-node.tsx",
				type: "registry:ui",
				target: "components/flow/generate-text-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/generate-text-node.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"prompt-crafter-node": {
		name: "prompt-crafter-node",
		description: "",
		type: "registry:ui",
		registryDependencies: [
			"button",
			"separator",
			"popover",
			"command",
			"http://localhost:4567/r/node-header-status.json",
			"http://localhost:4567/r/editable-handle.json",
			"http://localhost:4567/r/node-header.json",
			"http://localhost:4567/r/labeled-handle.json",
			"http://localhost:4567/r/base-node.json",
		],
		files: [
			{
				path: "./src/registry/ui/flow/prompt-crafter-node.tsx",
				type: "registry:ui",
				target: "components/flow/prompt-crafter-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/prompt-crafter-node.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"text-input-node": {
		name: "text-input-node",
		description: "",
		type: "registry:ui",
		registryDependencies: [
			"textarea",
			"separator",
			"http://localhost:4567/r/labeled-handle.json",
			"http://localhost:4567/r/node-header.json",
			"http://localhost:4567/r/resizable-node.json",
		],
		files: [
			{
				path: "./src/registry/ui/flow/text-input-node.tsx",
				type: "registry:ui",
				target: "components/flow/text-input-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/text-input-node.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"visualize-text-node": {
		name: "visualize-text-node",
		description: "",
		type: "registry:ui",
		registryDependencies: [
			"separator",
			"http://localhost:4567/r/markdown-content.json",
			"http://localhost:4567/r/labeled-handle.json",
			"http://localhost:4567/r/node-header.json",
			"http://localhost:4567/r/resizable-node.json",
		],
		files: [
			{
				path: "./src/registry/ui/flow/visualize-text-node.tsx",
				type: "registry:ui",
				target: "components/flow/visualize-text-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/ui/flow/visualize-text-node.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"base-handle": {
		name: "base-handle",
		description: "",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/base-handle.tsx",
				type: "registry:ui",
				target: "components/flow/base-handle.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/base-handle.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"labeled-handle": {
		name: "labeled-handle",
		description: "",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/labeled-handle.tsx",
				type: "registry:ui",
				target: "components/flow/labeled-handle.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/labeled-handle.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"base-node": {
		name: "base-node",
		description: "",
		type: "registry:ui",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/ui/flow/base-node.tsx",
				type: "registry:ui",
				target: "components/flow/base-node.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/base-node.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"node-header": {
		name: "node-header",
		description: "",
		type: "registry:ui",
		registryDependencies: ["button", "dropdown-menu"],
		files: [
			{
				path: "./src/registry/ui/flow/node-header.tsx",
				type: "registry:ui",
				target: "components/flow/node-header.tsx",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/flow/node-header.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"tool-invocation": {
		name: "tool-invocation",
		description: "",
		type: "registry:ui",
		registryDependencies: ["card", "collapsible"],
		files: [
			{
				path: "./src/registry/ui/tool-invocation.tsx",
				type: "registry:ui",
				target: "",
			},
			{
				path: "./src/registry/lib/id-to-readable-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/ui/tool-invocation.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"use-textarea-resize": {
		name: "use-textarea-resize",
		description: "",
		type: "registry:hook",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/hooks/use-textarea-resize.ts",
				type: "registry:hook",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/hooks/use-textarea-resize.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-utils": {
		name: "jsx-utils",
		description: "A set of utilities for working with JSX.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/lib/jsx-utils.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/lib/jsx-utils.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"id-to-readable-text": {
		name: "id-to-readable-text",
		description: "A utility for converting an ID to a readable text.",
		type: "registry:lib",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/lib/id-to-readable-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/lib/id-to-readable-text.ts");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-demo-mentions": {
		name: "chat-input-demo-mentions",
		description: "",
		type: "registry:example",
		registryDependencies: ["http://localhost:4567/r/chat-input.json"],
		files: [
			{
				path: "./src/registry/examples/chat-input-demo-mentions.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-demo-mentions.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-with-addons": {
		name: "chat-input-with-addons",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-input-with-addons.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-with-addons.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-input-demo-simple": {
		name: "chat-input-demo-simple",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-input-demo-simple.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-input-demo-simple.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-content-demo": {
		name: "markdown-content-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/markdown-content-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/markdown-content-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"markdown-streaming-demo": {
		name: "markdown-streaming-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/markdown-streaming-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/markdown-streaming-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo": {
		name: "chat-message-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-simple": {
		name: "chat-message-demo-simple",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-simple.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-simple.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-demo-avatar-image": {
		name: "chat-message-demo-avatar-image",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-demo-avatar-image.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-demo-avatar-image.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo": {
		name: "chat-message-area-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo-alignment": {
		name: "chat-message-area-demo-alignment",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo-alignment.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo-alignment.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-message-area-demo-streaming": {
		name: "chat-message-area-demo-streaming",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/chat-message-area-demo-streaming.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/chat-message-area-demo-streaming.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer-demo": {
		name: "jsx-renderer-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["http://localhost:4567/r/jsx-renderer.json"],
		files: [
			{
				path: "./src/registry/examples/jsx-renderer-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/jsx-renderer-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer-disabled-demo": {
		name: "jsx-renderer-disabled-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["http://localhost:4567/r/jsx-renderer.json"],
		files: [
			{
				path: "./src/registry/examples/jsx-renderer-disabled-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/jsx-renderer-disabled-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"jsx-renderer-streaming-demo": {
		name: "jsx-renderer-streaming-demo",
		description: "",
		type: "registry:example",
		registryDependencies: ["http://localhost:4567/r/jsx-renderer.json"],
		files: [
			{
				path: "./src/registry/examples/jsx-renderer-streaming-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/jsx-renderer-streaming-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector-demo": {
		name: "model-selector-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/model-selector-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/model-selector-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"model-selector-disabled-demo": {
		name: "model-selector-disabled-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/model-selector-disabled-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/model-selector-disabled-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"resizable-node-demo": {
		name: "resizable-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/resizable-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/resizable-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"visualize-text-node-demo": {
		name: "visualize-text-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/visualize-text-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/visualize-text-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"prompt-crafter-node-demo": {
		name: "prompt-crafter-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/prompt-crafter-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/prompt-crafter-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"text-input-node-demo": {
		name: "text-input-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/text-input-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/text-input-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"generate-text-node-demo": {
		name: "generate-text-node-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/generate-text-node-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/generate-text-node-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"editable-handle-demo": {
		name: "editable-handle-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/editable-handle-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/editable-handle-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"status-edge-demo": {
		name: "status-edge-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/status-edge-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/status-edge-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"tool-invocation-demo": {
		name: "tool-invocation-demo",
		description: "",
		type: "registry:example",
		registryDependencies: undefined,
		files: [
			{
				path: "./src/registry/examples/tool-invocation-demo.tsx",
				type: "registry:example",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/examples/tool-invocation-demo.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: undefined,
		meta: undefined,
	},
	"chat-01": {
		name: "chat-01",
		description: "A simple chat page.",
		type: "registry:block",
		registryDependencies: [
			"card",
			"breadcrumb",
			"separator",
			"sidebar",
			"tooltip",
			"button",
			"avatar",
			"dropdown-menu",
			"http://localhost:4567/r/chat-input.json",
			"http://localhost:4567/r/chat-message-area.json",
			"http://localhost:4567/r/chat-message.json",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-01/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-01/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-01/lib/config.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-layout.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-layout-skeleton.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-sidebar.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-main-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-secondary-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/layout/app-user-nav.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/chat/chat-main.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/chat/chat-header.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/chat-01/components/chat/chat-content.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-01/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
	"chat-02": {
		name: "chat-02",
		description: "A chat in a sidebar.",
		type: "registry:block",
		registryDependencies: [
			"sidebar",
			"breadcrumb",
			"http://localhost:4567/r/chat-input.json",
			"http://localhost:4567/r/chat-message-area.json",
			"http://localhost:4567/r/chat-message.json",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-02/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-02/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-02/components/app-sidebar.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-02/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
	"chat-03": {
		name: "chat-03",
		description: "A chat in a popover.",
		type: "registry:block",
		registryDependencies: [
			"popover",
			"button",
			"http://localhost:4567/r/chat-input.json",
			"http://localhost:4567/r/chat-message-area.json",
			"http://localhost:4567/r/chat-message.json",
		],
		files: [
			{
				path: "./src/registry/blocks/chat-03/page.tsx",
				type: "registry:page",
				target: "app/chat/page.tsx",
			},
			{
				path: "./src/registry/blocks/chat-03/route.ts",
				type: "registry:page",
				target: "app/api/ai/chat/route.ts",
			},
			{
				path: "./src/registry/blocks/chat-03/components/chat.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/chat-03/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["chat"],
		meta: undefined,
	},
	"app-01": {
		name: "app-01",
		description: "A app with generative UI capabilities.",
		type: "registry:block",
		registryDependencies: [
			"avatar",
			"input",
			"label",
			"tabs",
			"resizable",
			"breadcrumb",
			"button",
			"toggle-group",
			"switch",
			"separator",
			"card",
			"badge",
			"dialog",
			"slider",
			"http://localhost:4567/r/chat-input.json",
			"http://localhost:4567/r/chat-message-area.json",
			"http://localhost:4567/r/chat-message.json",
			"http://localhost:4567/r/jsx-renderer.json",
			"http://localhost:4567/r/jsx-utils.json",
		],
		files: [
			{
				path: "./src/registry/blocks/app-01/page.tsx",
				type: "registry:page",
				target: "app/generative-ui/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-01/canvas/page.tsx",
				type: "registry:page",
				target: "app/canvas/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-01/route.ts",
				type: "registry:page",
				target: "app/api/ai/generate/route.ts",
			},
			{
				path: "./src/registry/blocks/app-01/hooks/generation-store.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/versions.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/editor-layout.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/editor-toolbar.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/code-editor.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/preview.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/chat-dialog.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-01/components/copy-button.tsx",
				type: "registry:component",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/app-01/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["app"],
		meta: undefined,
	},
	"app-02": {
		name: "app-02",
		description: "A persona generator app with structured outputs.",
		type: "registry:block",
		registryDependencies: [
			"dialog",
			"button",
			"input",
			"textarea",
			"label",
			"scroll-area",
			"form",
			"skeleton",
			"card",
			"avatar",
		],
		files: [
			{
				path: "./src/registry/blocks/app-02/page.tsx",
				type: "registry:page",
				target: "app/persona/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-02/route.ts",
				type: "registry:page",
				target: "app/api/ai/persona/route.ts",
			},
			{
				path: "./src/registry/blocks/app-02/components/persona-display.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-02/lib/persona.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-02/lib/example-businesses.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/app-02/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["app"],
		meta: undefined,
	},
	"app-03": {
		name: "app-03",
		description: "An X profile bio generator app.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"dialog",
			"input",
			"textarea",
			"form",
			"label",
			"select",
			"skeleton",
			"avatar",
		],
		files: [
			{
				path: "./src/registry/blocks/app-03/page.tsx",
				type: "registry:page",
				target: "app/x-profile/page.tsx",
			},
			{
				path: "./src/registry/blocks/app-03/layout.tsx",
				type: "registry:page",
				target: "app/x-profile/layout.tsx",
			},
			{
				path: "./src/registry/blocks/app-03/route.ts",
				type: "registry:page",
				target: "app/api/ai/x-profile/route.ts",
			},
			{
				path: "./src/registry/blocks/app-03/components/profile-generate-dialog.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/components/x-preview.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/components/toolbar.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/components/theme-toggle.tsx",
				type: "registry:component",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/lib/x.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/blocks/app-03/lib/profile-examples.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/app-03/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["app"],
		meta: undefined,
	},
	"flow-chain": {
		name: "flow-chain",
		description: "Agentic chain workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"http://localhost:4567/r/generate-text-node.json",
			"http://localhost:4567/r/prompt-crafter-node.json",
			"http://localhost:4567/r/text-input-node.json",
			"http://localhost:4567/r/visualize-text-node.json",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-chain/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-chain/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-chain/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-chain/lib/news-summarization-chain.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/flow-chain/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
	"flow-routing": {
		name: "flow-routing",
		description: "Agentic routing workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"http://localhost:4567/r/generate-text-node.json",
			"http://localhost:4567/r/prompt-crafter-node.json",
			"http://localhost:4567/r/text-input-node.json",
			"http://localhost:4567/r/visualize-text-node.json",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-routing/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-routing/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-routing/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-routing/lib/content-creator-routing.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import("@/registry/blocks/flow-routing/page.tsx");
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
	"flow-parallelization": {
		name: "flow-parallelization",
		description: "Agentic parallelization workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"http://localhost:4567/r/generate-text-node.json",
			"http://localhost:4567/r/prompt-crafter-node.json",
			"http://localhost:4567/r/text-input-node.json",
			"http://localhost:4567/r/visualize-text-node.json",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-parallelization/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-parallelization/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-parallelization/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-parallelization/lib/exam-creator-parallelization.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/blocks/flow-parallelization/page.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
	"flow-orchestrator": {
		name: "flow-orchestrator",
		description: "Agentic orchestrator workflow.",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"dialog",
			"input",
			"textarea",
			"sonner",
			"http://localhost:4567/r/generate-text-node.json",
			"http://localhost:4567/r/prompt-crafter-node.json",
			"http://localhost:4567/r/text-input-node.json",
			"http://localhost:4567/r/visualize-text-node.json",
		],
		files: [
			{
				path: "./src/registry/blocks/flow-orchestrator/page.tsx",
				type: "registry:page",
				target: "app/workflow/page.tsx",
			},
			{
				path: "./src/registry/blocks/flow-orchestrator/route.ts",
				type: "registry:page",
				target: "app/api/workflow/execute/route.ts",
			},
			{
				path: "./src/registry/blocks/flow-orchestrator/components/nodes-panel.tsx",
				type: "registry:component",
				target: "components/flow/nodes-panel.tsx",
			},
			{
				path: "./src/registry/blocks/flow-orchestrator/lib/developer-tasks-orchestrator.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/ui/flow/status-edge-controller.tsx",
				type: "registry:component",
				target: "components/flow/status-edge-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/visualize-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/visualize-text-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/text-input-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/text-input-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/prompt-crafter-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/prompt-crafter-node-controller.tsx",
			},
			{
				path: "./src/registry/ui/flow/generate-text-node-controller.tsx",
				type: "registry:component",
				target: "components/flow/generate-text-node-controller.tsx",
			},
			{
				path: "./src/registry/hooks/flow/use-workflow.ts",
				type: "registry:hook",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-client.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/sse-workflow-execution-engine.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/server-node-processors.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/node-factory.ts",
				type: "registry:lib",
				target: "",
			},
			{
				path: "./src/registry/lib/flow/generate-ai-text.ts",
				type: "registry:lib",
				target: "",
			},
		],
		component: React.lazy(async () => {
			const mod = await import(
				"@/registry/blocks/flow-orchestrator/page.tsx"
			);
			const exportName =
				Object.keys(mod).find(
					(key) =>
						typeof mod[key] === "function" ||
						typeof mod[key] === "object",
				) || item.name;
			return { default: mod.default || mod[exportName] };
		}),
		categories: ["flow"],
		meta: undefined,
	},
};
